### ISSUE TITLE
As a user, I want to easily see all of my contacts that match my search criteria in contact merge, so I can find the correct contacts to merge.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#132] opened 2013-12-03 22:44 UTC
from jamesmelville on gitHub:

The page should implement pagination over the returned list of Contacts. For example it is possible to have a case where the search criteria match a large number of records and it is not possible to refine the criteria further to limit that list. If the records you want to merge don't appear in the top 20 then you're out of luck. (and SOSL can now return up to 2,000 results).

**Comment by davidhabib** [comment] 2015-04-21 20:55
duplicate of #349

**Comment by mrbelvedere** [comment] 2015-04-21 20:56
Story deleted from ScrumDo

**Closed by davidhabib** 2015-04-21 20:55 UTC
Labels: enhancement
