### ISSUE TITLE
Household issue

### ISSUE THREAD

**Issue by kmorgan007** [SalesforceFoundation/Cumulus#2185] opened 2016-07-27 18:32 UTC
With this new update I'm not able to add a contact to a household. I go into a household and type in the name of the person I want to add. The name and address pop up with a plus sign, but nothing happens when I click on the plus sign. I'm not receiving the old merge this contact message.

**Comment by davidhabib** [comment] 2016-07-27 19:00
if the contact was the only person on the household, we don't prompt.  we just add the contact directly.  Did the contact appear or not?  Also, what browser are you using?

**Comment by kmorgan007** [comment] 2016-07-27 19:07
The contact I want to add to the household does appear in the search box. There is a new plus sign that acts like I should be able to click on it to add, but nothing happens. I'm using Mozilla, but it does seem to be working in Chrome.

**Comment by kmorgan007** [comment] 2016-07-27 19:10
And I just received two errors when adding the contact to the household in Chrome.
First email:
 Error #1: 

Error Type: Other
Error Date: 2016-07-27 19:07:43
Message: "unable to obtain exclusive access to this record"
https://na34.salesforce.com/0036100000UHBmfAAH

Stack Trace:
 null
 Second email:
Errors:

----------
 Error #1: 

Error Type: System.DmlException
Error Date: 2016-07-27 19:07:42
Message: "Update failed. First exception on row 0 with id 0016100000T30mhAAB; first error: UNABLE_TO_LOCK_ROW, unable to obtain exclusive access to this record: []"

Stack Trace:
 Stacktrace available at the time of saving the record - (npsp)

**Comment by chrismcmahon** [comment] 2016-07-27 19:12
kmorgan007 what version of Firefox are you using?

**Comment by kmorgan007** [comment] 2016-07-27 19:17
I'm using version 47.0.1

**Comment by davidhabib** [comment] 2016-07-27 19:47
so it sounds like two unrelated issues.
1. in some browsers, our + button in the autocomplete control does not seem to work.
2. we hit some record locking errors when accounts are merged.

I'm aware of #2 already, and working on a fix. #2174 

@chrismcmahon I'll leave it to you to flush out the browser issues and enter the details on which browsers have this problem.  thanks!

**Comment by kmorgan007** [comment] 2016-07-27 20:20
So should I have my team just work in Chrome until I hear back?

**Comment by davidhabib** [comment] 2016-07-27 20:22
yes, I'm afraid so.  thanks.

**Comment by kmorgan007** [comment] 2016-07-27 20:22
No worries!! Thanks for all the quick responses!

**Comment by chrismcmahon** [comment] 2016-07-27 20:30
I tried Firefox 47.0.1 on OSX 10.10.5 and also Windows10 and I was able to select a Contact from the search results in the new Manage Household page using the circle-plus icon with no problem.  I updated the Selenium automated test build to use Firefox 47 on Windows 8.1 and also had no problem.

**Comment by kmorgan007** [comment] 2016-07-27 20:35
I'm using Windows 7 and it's still not working in Firefox.

**Comment by davidhabib** [comment] 2016-07-27 21:20
At this point @kmorgan007 , we can't reproduce the click issue on Win7 and Firefox 47.  So I'm going to recommend you enter a support case with Salesforce Support, and make sure you clearly identify it with NPSP.  Here are instructions on doing that.  https://powerofus.force.com/articles/Resource/How-to-log-a-tech-support-ticket-with-salesforce-com
thanks.

**Closed by davidhabib** 2016-07-27 21:20 UTC
