### ISSUE TITLE
BUG: When an opportunity is created via Lead Conversion, duplicate primary contact roles are generated for the oppty

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#1388] opened 2015-02-17 18:29 UTC
Replication instructions: 
Create a lead with a company of 'self'.  Click 'Convert', uncheck the 'Do not create Opportunity on Conversion' box, click 'Convert', note two Contact Roles for the new Contact/Oppty are created, both primary, one with the NPSP-defined default role, the other blank. 

https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000007UuJC&tab=sfdc.ProfilePlatformFeed&fId=0D58000001nILd5&emtm=1424188398094&s1nid=0DB800000004Fa7&OpenCommentForEdit=1&fromEmail=1&emkind=chatterCommentNotification&s1ext=0&s1oid=00D00000000hWLM&s1uid=00580000003egB0

**Comment by davidhabib** [comment] 2015-05-11 22:32
@kbromer I cannot reproduce, and I see that our lead convert code has logic to deal with this.  but in the hub thread, you mention that you finally could reproduce it.  what is the secret?  thanks.

**Comment by davidhabib** [comment] 2015-05-11 22:35
@kbromer Never mind.  I see that I did fix it in March!

**Comment by kbromer** [comment] 2015-05-12 16:34
Way to go past-Dave!

**Comment by pankaj90** [comment] 2015-07-08 19:14
@davidhabib  I just encountered same issues with NPSP 3.45
After converting a lead and creating an Opportunity on conversion causes duplicate contact roles to be created with both marked as primary and role as blank value. Please help.

**Comment by AshwinPandole** [comment] 2015-07-09 05:00
Receiving the same issue in my org with version 3.45
We have a demo scheduled with customer shortly. Can you please assist.
Thanks a lot.

**Comment by davidhabib** [comment] 2015-08-10 15:20
several people are reporting still seeing this issue, so reopening so we can investigate again.  For those on this lists still seeing this issue, please provide details:
1. which version of NPSP?
2. which account model?
3. converting to a new contact or merging an existing contact?
4. does it happen for all lead conversions, or only some?

**Comment by davidhabib** [comment] 2015-08-12 03:33
@kbromer @njjc I am stumped by this.  In the org for Daniel Gross (Brandworkers), I can consistently reproduce the problem.  Looking at the debug log, I can see why it happens.  In the Opportunity AfterUpdate, we call OPP_OpportunityContactRoles_TDTM which queries for any existing Primary OCR's on the opp, and finds none.  Thus it creates a new primary OCR with our Donor role.  But Salesforce is also creating a default OCR marked Primary with no role, since no Role is set as default. 

1. our query doesn't find this Salesforce created OCR, so I can only assume our trigger is running before the system creates the OCR.  But then why doesn't this reproduce in all of our orgs?

2. If the Salesforce OCR was already created, then why doesn't the query find it?

There is OLD code in LeadConvert to detect these duplicate OCR's and remove the dup, but it was only added for the converting to an existing contact scenario.  Not sure why it would only be an issue for converting to an existing rather than new, and also I can't explain why I cannot reproduce.

I'm out of ideas and looking for new thoughts?

**Comment by davidhabib** [comment] 2015-08-12 03:47
@kbromer @njjc I just reread the entire thread from the original hub post, https://powerofus.force.com/0D58000001nILd5, and definitely some users are saying it is not consistently happening.  This make me really wonder if it is a timing issue depending on when Salesforce creates the OCR and when our trigger runs and looks for it.  We could certainly modify the Lead Convert code to always search for the duplicate contact roles after the convert, and perform any cleanup (rather than just doing it in some scenarios).  I really hate changing code without being able to reproduce the bug and then test the fix, but unless someone has a better idea...

**Comment by tcdeselms** [comment] 2015-08-12 15:28
@davidhabib This bug is also happening in my Salesforce instance. We have are running version Summer 2015 on Enterprise Edition. Our account model is Household Account. The contact role duplication happens on all lead conversions (merging and creating new) that I designate to create a new Opportunity.

**Comment by mrbelvedere** [comment] 2015-09-28 19:24
Included in beta release version 3.52 (Beta 3) and higher

**Comment by mrbelvedere** [comment] 2015-10-07 00:14
Included in production release version 3.52

**Comment by cdcarter** [comment] 2016-05-24 18:16
I have an org displaying this behavior on 3.72, HH account model, on conversion of a NEW contact, and appears to be happening consistently. Looking at the current source (https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/LD_LeadConvertOverride_CTRL.cls) line 419 reads like it is still only avoiding duplicate OCRs on existing contacts (`strConId != 'NEW_CONTACT'`).

Happy to grant login access for this org. I have not been able to repro in a clean org, but I have seen more than one reference to the OCR that standard lead conversion creates being weird.

**Comment by davidhabib** [comment] 2016-05-24 19:54
**lurch: add

**Comment by LurchTheButler** [comment] 2016-05-24 19:55
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003oKmtAAE" target="_blank">W-010477</a>

**Comment by samlimster** [comment] 2016-06-03 14:45
I'm seeing this on my org as well.  Is there a workaround to avoid this until a fix is completed?

Thanks all!

**Comment by davidhabib** [comment] 2016-06-14 21:30
@cdcarter I need the orgId for your org that reproduces this problem.  thanks.

**Comment by cdcarter** [comment] 2016-06-15 18:14
Hey Dave, sorry for the delay, I didn't get a notif on this from Github! The org I granted login access to is 00D17000000BWMv. Thank you so much for taking a look! I'm stumped.

**Comment by davidhabib** [comment] 2016-06-15 18:33
no problem Christian.  I got the orgId from support.  Yep, it reproduces in your org!  Why not in any of my vanilla npsp orgs, no clue!  But we've had a fix for this in the code since years ago by whomever originally wrote it.  but it was always doing it just for the existing contact scenario.  I'm going to go ahead and change it to also do this logic for the new contact scenario.  wish I understood why it happens in some orgs, but not others, but at this point I just need to go with the fix and move on!  thanks.

**Comment by samlimster** [comment] 2016-06-16 02:01
Thankd you, David!  I'm looking forward to the fix.

Do you know what we can do with the contacts that already been duplicated?  Will there be a way to clean things up?

Thanks again!

**Comment by davidhabib** [comment] 2016-06-16 03:38
we do not have plans to write a utility to delete the duplicates.  you can run the report "Opportunities with Primary Contact Roles" in the NPSP Health Check reports folder, to see which opps have duplicate roles, and then delete them manually, or with an external tool.

**Comment by samlimster** [comment] 2016-06-16 03:49
Thanks, David.

Maybe I'm seeing a different issue.  I'm seeing 2 links to the same Contact.  i.e. if I delete one, I delete the other as well.  Have you seen this behaviour before?

Thanks again, David!

**Comment by judisohn** [comment] 2016-06-16 09:09
It's because you're clicking Del from the Contact record's related list which is deleting the entire Opportunity. Instead go to the Opportunity, scroll to the Contact Role section and delete the duplicate there.

You should also be able to use something like DemandTools (donated to nonprofits) to merge the duplicate Contact Role records which might be a lot easier to identify and deal with in bulk.

**Comment by cdcarter** [comment] 2016-06-16 15:00
@davidhabib -- it is horrifyingly frustrating to get a clean repro of this! I haven't been able to get it in an unmanaged version of the package yet. Oy! In any case, I'm so glad that the fix is simple enough. Thanks so much for looking at this!

**Closed** 2016-06-21 16:17 UTC
Labels: bug

**Comment by samlimster** [comment] 2016-07-06 04:19
@davidhabib, Thanks so much for fixing this!  

Has your update made it into the latest load yet?  I tried upgrading to NPSP 3.75 and tried doing some conversions and I'm still getting duplicated contact roles.

Thanks again!

**Comment by davidhabib** [comment] 2016-07-06 04:33
@jlantz Can you tell which version has this fix (from pull request 2120).  Even though the pull request had this fix listed, I don't see it listed in any release notes.  thanks.

**Comment by davidhabib** [comment] 2016-07-07 02:41
so I verified that our fix is in 3.75.  @cdcarter, @pankaj90, @AshwinPandole, @tcdeselms, @samlimster  can you all verify whether this problem is still occurring in your org, after confirming you have 3.75?  thanks all!

**Comment by samlimster** [comment] 2016-07-07 04:20
Hi David.

Yes, here's a screen shot on my org:

[image: Inline image 1]

Here's the NPSP version:

[image: Inline image 2]

Thanks, David!

**Comment by cdcarter** [comment] 2016-07-07 16:05
Appears to be fixed in my 3.76 org.

**Comment by samlimster** [comment] 2016-11-11 18:10
It looks like this issue might be caused by not actually using the NPSP lead conversion tool.  I'm using the default salesforce lead conversion which is creating it's own contact role, but some NPSP trigger is still running and creating it's own contact role.

Is there any way I can turn one of them off?

Thanks!
