### ISSUE TITLE
Recurring Donation - Refresh Opportunities not updating with new values

### ISSUE THREAD

**Issue by alphasys** [SalesforceFoundation/Cumulus#1697] opened 2015-09-02 14:47 UTC
If the Recurring Donation object is updated (i.e. Amount, Campaign, Custom Fields), the Refresh Opportunities button doesn't update the mapped fields in the open child Opportunities. Likewise if the instalment period is changed (for example from monthly to quarterly), the previously created monthly Opportunities still exist.

Ideally when the Refresh Opportunities button is selected, all currently open child Opportunities are deleted. Then when the action method to refresh the RD is run, new child Opportunities (with the correct schedule and field mappings) will be created in line with the current RD.

**Comment by davidhabib** [comment] 2015-10-01 00:00
I cannot reproduce this problem, and I believe it was solved back in May 2015 by an external contribution.  @alphasys What specific version of NPSP are you running?

**Comment by chrismcmahon** [comment] 2015-10-01 00:25
@davidhabib I reproduced it quite nicely and I'd be happy to get you access to my org. 
![screen shot 2015-09-30 at 5 23 38 pm](https://cloud.githubusercontent.com/assets/204643/10210148/3550b600-6798-11e5-9046-cbc3e2c0ff99.png)

**Comment by alphasys** [comment] 2015-10-01 00:29
From what I can gather, orgs that I created before the fix have this issue. In contrast when I try to recreate the issue on orgs created since June 2015, the opportunities appear to be refreshing correctly (i.e. I'd change from monthly to quarterly and the 12 pledged monthly opportunities would become 4 pledged quarterly opportunities).

I can confirm all of my NPSP orgs are on version 3.

**Comment by davidhabib** [comment] 2015-10-01 15:47
I believe the issue was resolved in version 3.38.  If you can reproduce in an org that is updated to the latest (3.50 or later), then reopen this issue with the repro steps, grant us login access to the org, and provide the org's name and Id.  thanks.

**Comment by alphasys** [comment] 2015-10-01 22:42
Hi @davidhabib I don't have the ability to reopen the issue. However here are the reproduction steps:

Verified my sandbox is on the NPSP 3.51:
![sf recurring issue - npsp version](https://cloud.githubusercontent.com/assets/10205071/10235531/a616e4ec-68e0-11e5-894b-18d8200ba72a.PNG)

Created monthly recurring donation:
![sf recurring issue - monthly donation](https://cloud.githubusercontent.com/assets/10205071/10235563/d4c9d088-68e0-11e5-8974-1f804e6af39c.PNG)

Changed to quarterly recurring donation and pressed refresh opportunities: no change to opportunities
![sf recurring issue - quarterly donation](https://cloud.githubusercontent.com/assets/10205071/10235601/14d85e6a-68e1-11e5-8d28-d65c94119f43.PNG)

Login access has been granted to Salesforce.com Foundation Support. Org ID is 00DN0000000AQY5 with name MAF Australia (sandbox alphasys).

**Comment by davidhabib** [comment] 2015-10-02 04:42
I found the problem.  One of your field mappings (npe03__Installment_Period__c) was already being selected by our query, and we accidentally added it to the query a second time which generates a Salesforce error.  Now I now exactly how to fix this issue.  thanks.

	System.QueryException	duplicate field selected: npe03__Installment_Period__c			Stacktrace available at the time of saving the record - Class.npsp.RD_RecurringDonations.updateExistingOpps: line 755, column 1
Class.npsp.RD_RecurringDonations.handleRecurringDonationUpdate: line 899, column 1
Class.npsp.RD_RecurringDonations_TDTM.run: line 104, column 1
Class.npsp.TDTM_TriggerHandler.runClass: line 186, column 1
Class.npsp.TDTM_TriggerHandler.run: line 108, column 1
Trigger.npsp.TDTM_RecurringDonation: line 33, column 1

**Comment by alphasys** [comment] 2015-10-02 06:39
That's great news @davidhabib. Is there anything you need me to do on my end or anything we need to manually correct in other orgs with this issue?

**Comment by davidhabib** [comment] 2015-10-02 14:49
nothing to do right now.  once the release goes out that will have the fix (in about 2 weeks), you will want to refresh your Recurring Donations.  In the mean time, you can avoid the problem if you remove the recurring donation field mapping that included the Installment Period field.

**Comment by kbromer** [comment] 2015-10-05 03:06
**lurch: add

**Comment by LurchTheButler** [comment] 2015-10-05 03:10
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fZXAAY" target="_blank">W-008165</a>

**Closed** 2015-10-05 20:35 UTC
Labels: accepted, bug

**Comment by mrbelvedere** [comment] 2015-10-05 21:40
Included in beta release version 3.52 (Beta 11) and higher

**Comment by mrbelvedere** [comment] 2015-10-07 00:14
Included in production release version 3.52
