### ISSUE TITLE
Recurring Donations Home page should show appropriate "Total" but does not

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#2153] opened 2016-07-11 20:10 UTC
![screen shot 2016-07-11 at 12 46 56 pm](https://cloud.githubusercontent.com/assets/204643/16744869/fd8fc278-4767-11e6-893e-4bd6a1573285.png)

Steps to reproduce: 

From the individual Contact or Account page in NPSP, create a Recurring Donation. Fill in the minimum default values and save the Recurring Donation. 

Navigate to the Recurring Donation Home screen. The Recurring Donation you created should have its total values displayed here, but it is shown as zero. 

Note that a Recurring Donation with Open Ended Status of "Open" or "Closed" properly should not display an amount for Total. While displaying a "total amount collected so far" for such a Recurring Donation may be desirable, it is beyond the scope of this issue.

**Comment by judisohn** [comment] 2016-07-12 13:57
@chrismcmahon I'm confused as to how this is a bug? It's just a standard formula field that hinges on the Open Ended Status value not being Open, and either takes the amount if it's Divide By schedule type, or multiplies by the installments if it's Multiply By.

**Comment by davidhabib** [comment] 2018-02-07 01:02
closing, as this seems like a misunderstanding not a bug.

**Closed by davidhabib** 2018-02-07 01:02 UTC
Labels: bug
