### ISSUE TITLE
As a user, I would like to be able to specify an existing household account, when doing lead conversion.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1232] opened 2014-12-19 23:34 UTC
When using the NPSP Household accounts and the Lead Convert override button is there a way to also display the Household account name. For example if Jim Smith is an existing contact under the Jim Smith Household account and Jennifer Smith is a Lead, when you convert Jennifer Smith, is there a way to convert her Lead into the Existing Jim Smith Household account?

thread on the hub: https://powerofus.force.com/0D58000001hrBkL

**Comment by njjc** [comment] 2015-03-11 17:49
Duplicate of #1213

**Comment by njjc** [comment] 2015-03-11 17:55
@mrbelvedere :(

**Closed by njjc** 2015-03-11 17:55 UTC
Labels: enhancement

**Comment by tombriggs-pracedo** [comment] 2017-05-02 08:36
This still seems to be an issue? There is no way of handling converting multiple Leads into one existing Account in the Lead Conversion Screen. This makes the custom Lead Conversion page quite unusable!

**Comment by judisohn** [comment] 2017-05-02 11:36
Thanks for your feedback. The NPSP Lead Conversion relies on the standard lead conversion functionality. As that changes in Salesforce, we should hopefully be able to benefit from the improvements and incorporate them.
