### ISSUE TITLE
Add Health Check test to detect duplicate contact roles

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2082] opened 2016-05-12 20:31 UTC
to allow users to identify opps that might be double counted in rollups and soft credit rollups.  after we release this, we can then fix the double counting issue.

**Comment by davidhabib** [comment] 2016-05-12 20:31
**lurch: add

**Comment by LurchTheButler** [comment] 2016-05-12 20:35
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003n4yUAAQ" target="_blank">W-010292</a>

**Comment by davidhabib** [comment] 2016-05-12 23:08
dupe of #2022

**Comment by dospromptman** [comment] 2016-06-13 18:33
@davidhabib, I don't think this is a dupe of #2022.  Was there a different ticket that contains additional details?

**Comment by davidhabib** [comment] 2016-06-13 19:07
Oops!  I think i mixed up bugs.  I believe #2081 and #2022 are the dupes of eachother!

**Comment by mrbelvedere** [comment] 2016-07-06 14:01
Included in beta release version 3.76 (Beta 16) and higher

**Comment by mrbelvedere** [comment] 2016-07-06 16:59
Included in production release version 3.76

**Closed** 2016-07-20 19:37 UTC
Labels: accepted, feature-request
