### ISSUE TITLE
In Contact Merge, if Current Address lookup is selected on one contact and Mailing Address fields on another contact, an error is generated

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1691] opened 2015-08-27 12:30 UTC
Hub thread: https://powerofus.force.com/0D58000002GMUOX

**Comment by aturaki** [comment] 2015-08-27 13:19
I originally logged this on hub.  Let me know if you need more info or login access to org where issue occurs to investigate.
thanks

**Comment by davidhabib** [comment] 2015-09-29 16:17
org had two trigger handlers marked Async.  AFFL_Affilations_TDTM on Contact and REL_Relationships_Con_TDTM on Contact.  If I unchecked async REL_Relationships_Con_TDTM, then contact merge worked correctly.

with Async checked on, we hit an exception in runAsync().  Here is the error with NPSP error handling disabled (so we see the underlying error):

Errors

Merge failed. First exception on row 0 with id 0033100002o1MKWAA2; first error: DELETE_FAILED, npsp.TDTM_Contact: execution of AfterDelete caused by: System.NullPointerException: Attempt to de-reference a null object Class.npsp.TDTM_TriggerHandler.runAsync: line 202, column 1 Class.npsp.TDTM_TriggerHandler.runClass: line 183, column 1 Class.npsp.TDTM_TriggerHandler.run: line 108, column 1 Trigger.npsp.TDTM_Contact: line 34, column 1: []
Failed to merge the contacts. Error: System.DmlException: Merge failed. First exception on row 0 with id 0033100002o1MKWAA2; first error: DELETE_FAILED, npsp.TDTM_Contact: execution of AfterDelete caused by: System.NullPointerException: Attempt to de-reference a null object Class.npsp.TDTM_TriggerHandler.runAsync: line 202, column 1 Class.npsp.TDTM_TriggerHandler.runClass: line 183, column 1 Class.npsp.TDTM_TriggerHandler.run: line 108, column 1 Trigger.npsp.TDTM_Contact: line 34, column 1: []

**Closed** 2015-09-29 20:14 UTC
Labels: bug

**Comment by mrbelvedere** [comment] 2015-09-29 21:18
Included in beta release version 3.52 (Beta 4) and higher

**Comment by mrbelvedere** [comment] 2015-10-07 00:14
Included in production release version 3.52
