### ISSUE TITLE
Lack of namespace prefixes causing naming collision

### ISSUE THREAD

**Issue by oneeyedjames** [SalesforceFoundation/Cumulus#4754] opened 2019-10-31 16:21 UTC
My organization recently had failures when deploying out to our production environment. Salesforce support is insistent that the compilation was failing because we have a lookup relationship to the Contact object with the same child relationship name (`Addresses__r`). Their proposed solution is to use the `npsp__` prefix in the packaged code, as below. Is this valid?

_from class ADDR_Contact_TDTM_
```
mapAccountIdAccount = new Map<Id,Account>([select Id, npe01__SYSTEM_AccountType__c,
(select Id from Addresses__r) from Account where Id IN :setAccountId]);
```
_should be changed to_
```
mapAccountIdAccount = new Map<Id,Account>([select Id, npe01__SYSTEM_AccountType__c,
(select Id from npsp__Addresses__r) from Account where Id IN :setAccountId]);
```

**Comment by coriobriensfdo** [comment] 2019-10-31 17:04
Actually @oneeyedjames I'll reopen this as we think it might be an issue that we'll need to address in the package to accomodate for core Salesforce functionality. 

Can you tell me a couple things:
1. Are you using Field Service Lightning? This comes with an Address object, so we think the conflict may be there. 
2. Can you give me your support Case number so we can take a look?

**Comment by coriobriensfdo** [comment] 2019-10-31 17:05
**Lurch: Add

**Comment by LurchTheButler** [comment] 2019-10-31 17:10
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HoCMQA0" target="_blank">W-037277</a>

**Comment by oneeyedjames** [comment] 2019-10-31 17:35
Thanks @coriobriensfdo,

1. We are not using Field Service Lightning, only SFDC + NPSP. Our address object is a custom object that we built in-house.
2. Our support case number is 24691055.

**Comment by coriobriensfdo** [comment] 2019-10-31 17:52
@oneeyedjames ok hold tight for a little bit. We've got some .org folks looking into this as we saw that you have a custom object for Address (so not from FSL) which changes things a bit.

**Comment by coriobriensfdo** [comment] 2019-11-05 21:38
@oneeyedjames 
I've done some further research and engaged with our Support Team and have confirmed that the NPSP managed package is coded correctly (despite .com support mentioning otherwise...sorry about that), and is referencing the namespace in the appropriate manner. 
Looks like the issue is related to [an issue ](https://success.salesforce.com/issues_view?title=namespaced-aggregate-fieldinfos-are-cached-incorrectly-on-entityinfoimpl-if-subscriber-org-has-non-namespaced-field-with-similar-child-relationship-n&Id=a1p3A000001YnWa) that will be addressed in the spring 20 release.
The suggested workaround is to disable "compile on deploy" until the core issues is resolved in Spring 20. 

I'll close out the issue now as it's not something we'll be addressing in the NPSP package, but let me know if you have any further questions via your post in the Hub.

**Closed by coriobriensfdo** 2019-11-05 21:38 UTC
