### ISSUE TITLE
test failures in client orgs in HH_OppContactRoles_TEST.cls

### ISSUE THREAD

**Issue by mscholtz** [SalesforceFoundation/Cumulus#1567] opened 2015-05-20 01:11 UTC
I have seen frequent test failures from this class in client orgs, often w/ some governor going over limit.  Today it's the following:

![image](https://cloud.githubusercontent.com/assets/931031/7717134/f182b92e-fe50-11e4-87f6-4b2232a5e8ba.png)

This is an issue b/c when we move to NPSP3 for a client, we always review NPSP3 tests to make sure there's not an incompatibility w/ their custom code/WF.  But when we get errs like this it's very hard to tell if something is really wrong, or if it's just a fragile test.

I can't debug this because there's a good dozen tests in here and the debug log craps out before it gets to the ones that are failing.  

The one suggestion I have is to use start/stop test in all your tests so that you get the extra overhead on governors.

**Comment by kbromer** [comment] 2015-10-09 15:59
**lurch: attach W-007372

**Comment by LurchTheButler** [comment] 2015-10-09 16:00
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZvAAI" target="_blank">W-007372</a>

**Comment by snugsfbay** [comment] 2016-03-21 20:49
We were unable to reproduce the problem at the Spring 16 NPSP Sprint.  Since the test class was updated in December, it may be that the updates fixed this problem.  Otherwise, we need more instruction to reproduce this problem in a developer org so we can investigate more.

**Comment by njjc** [comment] 2016-03-21 21:06
Closing until we have a reproducible case.

**Closed by njjc** 2016-03-21 21:06 UTC
Labels: accepted
