### ISSUE TITLE
System.QueryException on contact merge

### ISSUE THREAD

**Issue by AshwinPandole** [SalesforceFoundation/Cumulus#1584] opened 2015-05-29 05:34 UTC
@njjc 
Hi Nicolas,

Getting below exception while doing contact merge

![image](https://cloud.githubusercontent.com/assets/3069322/7877119/73569048-05f3-11e5-969a-611be16404b5.png)

below is the log while exception was inserted.

![image](https://cloud.githubusercontent.com/assets/3069322/7877133/953a40d8-05f3-11e5-85ec-d7a37ea23d01.png)

can you please assist.

**Comment by judisohn** [comment] 2015-05-29 09:35
Hi @AshwinPandole - it would be great if you could start a post on the Power of Us Hub in the NPSP group detailing a little bit more about your instance and situation. Do you have additional custom code or other apps? What version of NPSP? Account model? How many opportunities do these contacts have? Etc.

Our typical process is to collaborate with you and the community to troubleshoot errors in the Hub. Then once determined that it is indeed a general product bug/issue and the problem is identified in a reproducible and actionable way, it's updated here. 

Thanks!!

**Comment by davidhabib** [comment] 2015-06-09 19:40
same as #1591?

**Comment by davidhabib** [comment] 2015-06-09 20:51
fixed in NPSP version 3.41 which will be released to sandboxes hopefully on 6/10.

**Closed by davidhabib** 2015-06-09 20:51 UTC
