### ISSUE TITLE
Error: Apex trigger npsp.TDTM_Contact caused an unexpected exception

### ISSUE THREAD

**Issue by KalmanS** [SalesforceFoundation/Cumulus#1268] opened 2015-01-18 04:55 UTC
I see the Closed issues for the same problem here: https://github.com/SalesforceFoundation/Cumulus/issues/1082
I receive the error if Automatic Household Naming is TRUE or FALSE.   

I am only getting the error when I edit certain fields on the Contact record. Here is what is happening.
This is in a SB with Spring 15'

I am still getting the following error when I edit certain contact fields. These are the fields that cause the error. Other fields (I.e. OtherStreet, phone, email - do not cause the error).
MailingStreet
MailingCity
MailingState
MailingZip
Title
OtherCity
OtherZip
OtherState

Error:Apex trigger npsp.TDTM_Contact caused an unexpected exception, contact your administrator: npsp.TDTM_Contact: System.LimitException: npsp:Too many SOQL queries: 101

**Comment by kbromer** [comment] 2015-01-18 05:00
What version of the Nonprofit Starter Pack package are you running?

**Comment by KalmanS** [comment] 2015-01-18 05:12
Thanks for the quick reply Kevin.

We are running NPSP 3.30

Kalman

On Sat, Jan 17, 2015 at 10:00 PM, Kevin Bromer <notifications@github.com>
wrote:

> What version of the Nonprofit Starter Pack package are you running?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SalesforceFoundation/Cumulus/issues/1268#issuecomment-70396690>
> .
>



-- 

*Kalman Sweetwine*

**Comment by KalmanS** [comment] 2015-01-19 05:03
FYI - I am not seeing this error in prod.

**Comment by kbromer** [comment] 2015-01-19 15:33
Are the sandbox and prod NPSP versions the same?

**Comment by davidhabib** [comment] 2015-01-19 15:58
@jlantz do we have a Spring '15 instance yet that we are running tests on?

**Comment by jlantz** [comment] 2015-01-19 16:11
Not yet

**Comment by KalmanS** [comment] 2015-01-20 01:30
@kbromer - Yes - also have NPSP 3.30 in Prod.

**Comment by njjc** [comment] 2015-01-20 18:31
Hi @KalmanS, I have been trying to repro your bug in a spring15 org and haven't had any luck. Do you have a large amount of data in any objects?

**Comment by KalmanS** [comment] 2015-01-20 19:14
@njjc there is very limited data in this instance. There is a lot of development but we are not seeing other errors.

**Comment by njjc** [comment] 2015-01-20 19:28
Number of SOQL queries: 29 out of 100 is all I'm getting in my spring 15 org with a clean install for changing a contact address.

**Comment by njjc** [comment] 2015-01-27 17:13
I'll close this for now, let me know if there is new information that says we should reopen this issue.

**Closed** 2015-01-27 17:17 UTC

**Comment by KalmanS** [comment] 2015-01-27 17:19
Okay, I'll post any new info that may help.

**Comment by rodneyawhite** [comment] 2016-01-09 13:47
FYI, I am getting this error on a large data import into a sandbox. 

npsp version 3.60

Latest version of SFDC

On the upsert of a contact record, I get this following error: failed with status 400, response [{"message":"npsp.TDTM_Contact: System.LimitException: npsp:Too many SOQL queries: 101","errorCode":"CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY","fields":[]}],

**Comment by rodneyawhite** [comment] 2016-01-09 14:06
also, when I run the health check under the settings tab->system tools->heath check.

I get this error: npsp:Too many SOQL queries: 101
Error is in expression '{!runDetector}' in component <apex:commandButton> in page npsp:stg_panelhealthcheck: (npsp)

**Comment by kbromer** [comment] 2016-01-09 19:59
@rodneyawhite this could be caused by any number of things running in your org, and is being surfaced by the NPSP.  For example, if you have code that when you insert a Contact, it inserts another Contact, that normally single DML is now double.  Based on healthcheck surfacing your issue, that sounds like a probable cause.

**Comment by rodneyawhite** [comment] 2016-01-09 20:18
Thanks for following up.

FYI, this is a fairly new install of SFDC+NPSP.  (end of last year)

The triggers on the contact record are:
TDTM_Contact (Nonprofit Starter Pack package)
VOL_Contact_MaintainHours(Volunteers for Salesforce package)
ContactTrigger (College Forward SIS)

From the Volunteers for SFDC package (https://github.com/davidhabib/Volunteers-for-Salesforce/blob/master/src/triggers/VOL_Contact_MaintainHours.trigger), it doesn't look like they are inserting another contact record.

I have access to the CollegeForward source, which does some other referential checks to other objects on insert.

Also, this happens about half the time when I am doing an data import from a sandbox refresh.

I will try to repro, this with just the NPSP installed.
