### ISSUE TITLE
Recurring Donation Delete when Account/Contact Delete

### ISSUE THREAD

**Issue by TracyKronzak** [SalesforceFoundation/Cumulus#1834] opened 2015-11-21 00:24 UTC
When an Account is deleted in Salesforce, Opportunities will cascade delete.  Similarly, the NPSP makes some accommodation for Contact deletion as well.  However, can/should the Recurring Donation Object be included as part of the "cascade" if the master Account or Contact is deleted?  Right now, they will be orphaned, without Accounts, Contacts, or Opportunities associated with them.

**Comment by judisohn** [comment] 2015-11-21 07:29
**lurch: add

**Comment by LurchTheButler** [comment] 2015-11-21 07:30
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hJWAAY" target="_blank">W-008794</a>

**Comment by judisohn** [comment] 2016-11-30 15:18
Closing as this is a dupe of #2377 which is currently in progress.

**Closed by judisohn** 2016-11-30 15:18 UTC
Labels: accepted, enhancement
