### ISSUE TITLE
HealthCheck - npsp:Too many query rows: 50001

### ISSUE THREAD

**Issue by amazingjoe** [SalesforceFoundation/Cumulus#2022] opened 2016-03-29 16:07 UTC
In a full Sandbox I have performed an upgrade to the NPSP 3.69 and when I attempt to run the health check I get the following error:

npsp:Too many query rows: 50001
Error is in expression '{!runDetector}' in component <apex:commandButton> in page npsp:stg_panelhealthcheck: (npsp)

An unexpected error has occurred. Your solution provider has been notified. (npsp)

The instance I am running it on has around 150K+ Contacts which is perhaps what is throwing it off.

**Comment by judisohn** [comment] 2016-03-29 16:39
Hi @amazingjoe - thanks for the post. Do you have access to the Power of Us Hub? Best bet is to post there in the NPSP Group, as we prefer to help you troubleshoot there and save creating issues here for actionable items. I'm going to close this issue until we find a reproducible use case that would require a developer to do work. We can always reopen if that's the case.

Are you using a bucket account model where you have many contacts in the same account?

**Comment by davidhabib** [comment] 2016-03-30 15:53
I've looked in the error logs and found where we aren't handling large data volumes.  The method verifyNoMissingOppPayments() is running a soql query that can hit limits in orgs with large amounts of Opportunities.

**Comment by davidhabib** [comment] 2016-03-30 15:53
**lurch: add

**Comment by davidhabib** [comment] 2016-03-30 15:55
Error Log: https://foundation.my.salesforce.com/a0u80000004q56X

Apex script unhandled exception by user/organization: 0051A00000A83D4/00D80000000dXy4
Visualforce Page: /apex/npsp__STG_SettingsManager
caused by: System.LimitException: npsp:Too many query rows: 50001
Class.npsp.STG_PanelHealthCheck_CTRL.verifyNoMissingOppPayments: line 655, column 1
Class.npsp.STG_PanelHealthCheck_CTRL.runAllDetections: line 184, column 1
Class.npsp.STG_PanelHealthCheck_CTRL.runDetector: line 101, column 1

**Comment by LurchTheButler** [comment] 2016-03-30 15:55
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003QeqMAAS" target="_blank">W-009789</a>

**Comment by davidhabib** [comment] 2016-03-30 15:57
another different scenario.
Error Log: https://foundation.my.salesforce.com/a0u80000004pBlT
Apex script unhandled exception by user/organization: 005E0000000Lduo/00DE0000000aa6C
Visualforce Page: /apex/npsp__STG_SettingsManager
caused by: System.LimitException: npsp:Too many query rows: 50001
Class.npsp.STG_PanelHealthCheck_CTRL.verifyOppContactRoles: line 545, column 1
Class.npsp.STG_PanelHealthCheck_CTRL.runAllDetections: line 166, column 1
Class.npsp.STG_PanelHealthCheck_CTRL.runDetector: line 101, column 1

**Comment by judisohn** [comment] 2016-03-30 15:58
Thanks @davidhabib!

**Comment by judisohn** [comment] 2016-06-03 19:36
another thread: https://powerofus.force.com/0D58000002jtIwL

**Comment by dospromptman** [comment] 2016-06-11 17:35
I think the issue here is that the query row limit is per transaction, not a per query limit.

Most queries executed while performing the health check do have LIMIT clauses.  Most of these seem to use a limit value of 9,999.

However, queries that run earlier in the health check process can use up the query row limit, and later queries will trigger the limit exception, regardless of the amount specified in the LIMIT clause for those later queries.

I recommend we address this issue by doing some combination of the following:

* Modify the health check queries so that they access only the minimum number of records needed to detect an error condition.  They can report to the user whether an error condition was detected or not, but no longer will they be able to report to the user *how many* records did or did not meet the error conditions.  If the specific number of records really needs to be known, maybe the user could request that a separate query be executed and they can view the results, or they could use a report to view the erroneous records.
* Before each health check is run, use the Limits class to detect current limits usage.  If there is the possibility that executing that health check could exceed limits usage, that health check is skipped and a warning is emitted in the health check results instead.
* Instead of providing the user with only a 'Run Health Check' button, the user could be presented with a list of health checks, and the ability to activate a checkbox next to each health check to indicate that they want that health check to be executed after they click the run button.  The default would be all boxes checked.  The menu might not need be immediately visible, but could be hidden behind an accordion style drop-down.

**Comment by davidhabib** [comment] 2016-06-12 02:41
I wasn't aware that query row limit was per transaction, not per query.  I still think a first step is fixing STG_PanelHealthCheck_CTRL.verifyOppContactRoles to limit appropriately.  That is the only test I've been seeing in the logs that is generating the error.  All of the other queries are limiting.  Before we undertake such a major redesign of Health Check, let's make this fix, and then see if we still continue to see problems.

**Comment by kbromer** [comment] 2016-06-12 17:38
We'd definitely discussed wizard-ifying it in the past as well, which would force the user to click through various checks, and thereby separate the transactions.  Essentially a step-through process with an end-result report that we'd render once complete.  I think its probably worth investigating only if the limit for verifyOppContactRoles doesn't address it, and then I'm sure @mpusto can work her magic with UX to address the flow

**Comment by amazingjoe** [comment] 2016-06-12 20:53
I ran into this error two times and in both cases it was because there were
more than 50K Contact records associated with a particular bucket account
(as Judi suggested may be the problem). My suggestion would be to introduce
this scenario as one of the test cases for whatever solution is pursued.

If there was a wizard-ified interface and I could skip that particular
check if it failed/couldn't process due to the DML error then it would have
definitely allowed me to continue with the rest of the tests.

**Comment by dospromptman** [comment] 2016-06-13 17:55
After discussing with the team, I have added a `LIMIT` clause to the query in `verifyNoMissingOppPayments` health check in order to reduce query row limit usage.

@amazingjoe, keep an eye on future releases for this change, and please update this ticket if you continue to have limit issues with the health check.

**Closed** 2016-07-28 21:41 UTC
Labels: accepted, bug
