### ISSUE TITLE
Payment against Closed/Lost results in deleted record instead of error

### ISSUE THREAD

**Issue by jessingrass** [SalesforceFoundation/Cumulus#2766] opened 2017-09-22 19:03 UTC
Repro Steps:

1. Make an opportunity with a closed/lost stage
2. Select Payment > New Payment from Related Lists
3. Make a payment with required fields and an amount
4. Click save
5. EXPECTED RESULT: Error message
6. ACTUAL RESULT: A message shows up saying that the record has been deleted. The payment record appears in the recycle bin. The payment attempt cannot be undeleted. The original opportunity record IS NOT in the recycle bin.

**Comment by judisohn** [comment] 2017-09-23 17:13
Closing as a duplicate of #1824

**Closed by judisohn** 2017-09-23 17:13 UTC
